version: "2"
run:
  go: "1.26"
linters:
  enable:
    - gocritic
    - misspell
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net/http.Response).Body.Close
        - (database/sql).Rows.Close
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close
        - (*ktk-schedule/internal/storage.Storage).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*net/http.Server).ListenAndServe
        - (net/http.Server).ListenAndServe
        - encoding/json.Unmarshal
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
      enabled-tags:
        - diagnostic
        - performance
    misspell:
      locale: US
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
